### ISSUE TITLE
Vector of prediction capsule

### ISSUE THREAD

**Issue by AnushaMehta** [meet-minimalist/Capsule-Network#1]
Hello,
First of all, many thanks for this in depth tutorial on capsule network. It is said in the paper that the vector of capsule defines parameters which are related to orientation. 
I want to know what is the meaning of the vector of prediction capsule, can you please elaborate that? The parameters define which property? And can we reconstruct the image from those parameters? What if, I wanted to plotted them on graph?
I am a newbie in capsule networks and deep learning. I want to know how orientation details can be fetched from capsule network and how to visualize the process.
Thank you and regards.

**Comment by meet-minimalist** [comment]
@AnushaMehta 
I think you are talking about the output of Caps Net which is a vector of 10 x 16 dims. 10 dims for 10 classes and 16 dims for 16 various (unknown) properties. These vectors encode the input image in themselves. Like each of these 10 vectors will be having a length between 0 to 1 and the vector (of 16 dims) which has highest length will represent the actual output of the CapsNet. E.g. if 3rd vector has the highest length of 0.78 then the input image is surely represents '2'.

The authors' have tried to decode these vectors by training a decoder network with reconstruction loss along with Capsule Network training. (Please refer to the image attached in the repo / jupyter notebook). They took the output of CapsNet (which is highest value vector) and feed it to FC layers of 16 --> 512 --> 1024 --> 784 === reshaped to 28 x 28 to visualize what these 16 dimensional vectors represent. 

And if you go through my Jupyter Notebook (please download the notebook and then run it on your local machine as Github has no support for Jupyter Widgets which I have used to demonstrate the meaning of 16 dims vectors), I have done that exercise for further understanding. I have used feed a sample input to a trained CapsNet which followed by FC layers which were used during training. After feeding the input image, I get the 10 x 16 dims vectors and from that a predicted output vector of 1 x 16 dims. 

Now I am feeding this vector into the FC layers stack explicitly, to visualize what these 16 dims mean. With the help of sliders provided by Jupyter Notebook, you can manually change the individual values of each of these 16 dimensions of the vector and get the feel of what each dimension refers to. Some of these dimensions refer to stroke thickness or width or skew etc.

I hope now I have made you clear on this.

**Comment by AnushaMehta** [comment]
@meet-minimalist 
Thank you so much, sir.
By manually changing individual values of each of these 16 dimension, I can get what these dimension refer to, but where I can see this changes, whether it is in reconstructed image?
